config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  get 'posts/index'
  get 'categories/index'
  get "categories/:id", to: "categories#show", as: :category
  get "posts/:id", to: "posts#show", as: :post
  get "users/:id", to: "users#show", as: :author
  root to: 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :title, presence: true, uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  default_scope { order(updated_at: :desc) }
  has_one_attached :photo
  validates :title, presence: true
  validates :content, presence: true

  include PgSearch::Model
  pg_search_scope :global_search,
    against: { title: 'A', content: 'B' },
    associated_against: { user: [:full_name], category: [:title] },
    # ignoring: :accents,
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_one_attached :photo
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
  end

  def show
    @category = Category.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    if params[:query].present?
      @posts = Post.global_search(params[:query])
    else
      @posts = Post.all
    end
  end

  def show
    @post = Post.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h1>Toutes les catégories</h1>

app/views/categories/show.html.erb
<div class="main-container">
  <h1><%= @category.title %></h1>
  <div class="cards">
    <% @category.posts.each do |post| %>
      <div class="card">
        <% if post.photo.attached?  %>
          <%= cl_image_tag post.photo.key, class: "images" %>
        <% else %>
          <%= image_tag "post.jpg", class: "images" %>
        <% end %>
        <div class="details">
          <%= link_to post.category.title, category_path(post.category) %>
          <!-- <p>&nbsp- <%= post.updated_at.strftime("%e %B %Y") %></p> -->
          <p>&nbsp- <%= l(post.updated_at, :format => '%d %B %Y') %></p>
        </div>
        <div class="title">
          <h2><%= link_to post.title, post_path(post)  %></a></h2>
        </div>
        <div class="summary">
          <%= link_to post_path(post), style: "margin-left: 0px;" do %>
            <p><%= post.content %></p>
          <% end %>
        </div>
        <div class="author">
          <%= link_to author_path(post.user), style: "margin-left: 0px;" do %>
            <% if post.user.photo.attached? %>
              <%= cl_image_tag post.user.photo.key, height: 56, width: 56, crop: :fill, class: "avatar-large" %>
            <% else %>
              <%= image_tag "logo-avatar.jpg", class: "avatar-large" %>
            <% end %>
          <% end %>
          <div class="role">
            <%= link_to post.user.full_name, author_path(post.user) %></a>
            <p><%= post.user.title %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Le blog MorningCroissant</title>
    <meta name="description" content="Simplifier et sécuriser la location pour les locataires et pour les loueurs">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="site-content">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Simplifier et sécuriser la location</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/_category.html.erb
<div class="main-container">
  <div class="cards">
    <% category.posts.each do |post| %>
      <% if post != current_post %>
        <div class="card">
          <% if post.photo.attached?  %>
            <%= cl_image_tag post.photo.key, class: "images" %>
          <% else %>
            <%= image_tag "post.jpg", class: "images" %>
          <% end %>
          <div class="details">
            <%= link_to post.category.title, category_path(post.category) %>
            <!-- <p>&nbsp- <%= post.updated_at.strftime("%e %B %Y") %></p> -->
            <p>&nbsp- <%= l(post.updated_at, :format => '%d %B %Y') %></p>
          </div>
          <div class="title">
            <h2><%= link_to post.title, post_path(post)  %></h2>
          </div>
          <div class="summary">
            <%= link_to post_path(post), style: "margin-left: 0px;" do %>
              <p><%= post.content %></p>
            <% end %>
          </div>
          <div class="author">
            <%= link_to author_path(post.user), style: "margin-left: 0px;" do %>
              <% if post.user.photo.attached? %>
                <%= cl_image_tag post.user.photo.key, height: 56, width: 56, crop: :fill, class: "avatar-large" %>
              <% else %>
                <%= image_tag "logo-avatar.jpg", class: "avatar-large" %>
              <% end %>
            <% end %>
            <div class="role">
              <%= link_to post.user.full_name, author_path(post.user) %>
              <p><%= post.user.title %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main-container">
  <h1>Simplifier et sécuriser la location</h1>
  <div class="cards">
    <% @posts.each do |post| %>
      <div class="card">
        <% if post.photo.attached?  %>
          <%= cl_image_tag post.photo.key, class: "images" %>
        <% else %>
          <%= image_tag "post.jpg", class: "images" %>
        <% end %>
        <div class="details">
          <%= link_to post.category.title, category_path(post.category) %>
          <p>&nbsp- <%= l(post.updated_at, :format => '%d %B %Y') %></p>
        </div>
        <div class="title">
          <h2><%= link_to post.title, post_path(post)  %></h2>
        </div>
        <div class="summary">
          <%= link_to post_path(post), style: "margin-left: 0px;" do %>
            <p><%= post.content %></p>
          <% end %>
        </div>
        <div class="author">
          <%= link_to author_path(post.user), style: "margin-left: 0px;" do %>
            <% if post.user.photo.attached? %>
              <%= cl_image_tag post.user.photo.key, height: 56, width: 56, crop: :fill, class: "avatar-large" %>
            <% else %>
              <%= image_tag "logo-avatar.jpg", class: "avatar-large" %>
            <% end %>
          <% end %>
          <div class="role">
            <%= link_to post.user.full_name, author_path(post.user) %>
            <p><%= post.user.title %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post-wrapper">
  <div class="main-container">
    <h1><%= @post.title %></h1>
    <div class="post-header">
      <div class="border-center">
      </div>
      <div class="author center post-author">
        <% if @post.user.photo.attached? %>
          <%= cl_image_tag @post.user.photo.key, height: 56, width: 56, crop: :fill, class: "avatar-large" %>
        <% else %>
          <%= image_tag "logo-avatar.jpg", class: "avatar-large" %>
        <% end %>
        <div class="role">
          <%= link_to @post.user.full_name, author_path(@post.user), class: "hover-smooth" %></a>
          <p><%= @post.user.title %></p>
          <div class="details-show">
            <%= link_to @post.category.title, category_path(@post.category), class: "hover-smooth" %>
            <p style="margin-left: 0px;">&nbsp- <%= l(@post.updated_at, :format => '%d %B %Y') %></p>
          </div>
        </div>
      </div>
    <div class="border-center">
    </div>
    </div>
    <div class="post-picture">
      <% if @post.photo.attached? %>
        <%= cl_image_tag @post.photo.key, height: 300, width: 500, crop: :fill %>
      <% else %>
        <%= image_tag "post.jpg", height: 300, width: 500, crop: :fill %>
      <% end %>
    </div>
    <div class="post-sharing">
      <p>Partager cet article</p>
      <i class="fab fa-linkedin"></i>
      <i class="fab fa-twitter-square"></i>
      <i class="fab fa-facebook-square"></i>
    </div>
    <div class="post-content">
      <%= @post.content %>
      <div class="post-sharing">
        <p>Partager cet article</p>
        <i class="fab fa-linkedin"></i>
        <i class="fab fa-twitter-square"></i>
        <i class="fab fa-facebook-square"></i>
      </div>
    </div>
  </div>
</div>
<% if @post.category.posts.count > 1 %>
  <div class="category-wrapper">
    <div class="main-container">
      <h4>De la même catégorie</h4>
      <%= render "posts/category", category: @post.category, current_post: @post %>
    </div>
  </div>
<% else %>
  <body style="background-color: white;">
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="main-container">
      <div class="footer-intro">
        <p>Bonjour, nous c’est MorningCroissant, la place de marché  dédiée à la location de logements en moyenne et longue durée.<br>Notre mission ? Rendre la location plus simple, plus juste et plus sécurisée pour les locataires et les loueurs. Tout simplement :)</p>
      </div>
      <div class="footer-breadcrumb">
        <p>MC Blog > page 1 > page 2 > page 3</p>
      </div>
      <div class="footer-susbscribe">
        <p>Recevez nos derniers posts par email. Un par semaine. Pas de spam :)</p>
        <div class="susbscribe-form">
          <div class="subscribe-input">
            <p>Entrez votre adresse email</p>
          </div>
          <a href="#" class="btn-orange">S'abonner</a>
        </div>
      </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.jpg", alt: "Le blog MorningCroissant", class: "avatar" %>
    <h3>Blog</h3>
  <% end %>
  <%= form_tag posts_index_path, method: :get, class: "form-inline search-bar" do %>
    <i class="fas fa-search"></i>
    <%= text_field_tag :query,
      params[:query],
      placeholder: "Rechercher un article"
    %>
  <% end %>
  <!-- <div class="search-bar">
    <i class="fas fa-search"></i>
    <p>Rechercher un article</p>
  </div> -->

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <!-- navbar MC -->
    <%= link_to "Découvrir MorningCroissant", "https://www.morningcroissant.fr", class: "btn-blue", target: "_blank" %>
    <!-- navbar Le Wagon
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
 -->
  </div>
</div>

app/views/users/show.html.erb
<div class="main-container">
  <h1><%= @user.full_name %></h1>
  <div class="cards">
    <% @user.posts.each do |post| %>
      <div class="card">
        <% if post.photo.attached?  %>
          <%= cl_image_tag post.photo.key, class: "images" %>
        <% else %>
          <%= image_tag "post.jpg", class: "images" %>
        <% end %>
        <div class="details">
          <%= link_to post.category.title, category_path(post.category) %>
          <!-- <p>&nbsp- <%= post.updated_at.strftime("%e %B %Y") %></p> -->
          <p>&nbsp- <%= l(post.updated_at, :format => '%d %B %Y') %></p>
        </div>
        <div class="title">
          <h2><%= link_to post.title, post_path(post)  %></a></h2>
        </div>
        <div class="summary">
          <%= link_to post_path(post), style: "margin-left: 0px;" do %>
            <p><%= post.content %></p>
          <% end %>
        </div>
        <div class="author">
          <%= link_to author_path(post.user), style: "margin-left: 0px;" do %>
            <% if post.user.photo.attached? %>
              <%= cl_image_tag post.user.photo.key, height: 56, width: 56, crop: :fill, class: "avatar-large" %>
            <% else %>
              <%= image_tag "logo-avatar.jpg", class: "avatar-large" %>
            <% end %>
          <% end %>
          <div class="role">
            <%= link_to post.user.full_name, author_path(post.user) %></a>
            <p><%= post.user.title %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>